### ISSUE TITLE
Start project

### ISSUE THREAD

**Issue by tinivir** [mini-kep/full-app#1]
A standart Django app with Postgres

- [x] DB and models:
-- Datapoint model for Datapoint table in DB

- [x] Views
-- Datapoint view to work with Datapoint model

- [x] Tests
-- Testtin Datapoint view

Est. time 4 hours

**Comment by epogrebnyak** [comment]
Can you elaboarte what models and views?

**Comment by epogrebnyak** [comment]
Project started with 0c764fd49649028c6a5a3d53fea283773cc324d1
