### ISSUE TITLE
settings: branch production/local/other settings 

### ISSUE THREAD

**Issue by epogrebnyak** [mini-kep/full-app#13]
I think we need settings branching as in <https://stackoverflow.com/questions/1626326/how-to-manage-local-vs-production-settings-in-django/15325966#15325966>

I see there are two ways to achive switching .py fiels in ```settings``` directory or yaml config files. I slightly favour .py.

Follows #5

**Comment by epogrebnyak** [comment]
@tinivir - where are we on this?  should we do it now or later?

**Comment by Rub4ek** [comment]
Also, check this package:
https://django-configurations.readthedocs.io/en/stable/

It helps to keep settings more "dry"

```
from configurations import Configuration

class Base(Configuration):
    TIME_ZONE = 'Europe/Berlin'

class Dev(Base):
    DEBUG = True
    TEMPLATE_DEBUG = DEBUG

class Prod(Base):
    TIME_ZONE = 'America/New_York'
```

**Comment by epogrebnyak** [comment]
@Rub4ek - thanks will try to integrate this.

**Comment by epogrebnyak** [comment]
Usually do we need a local and a production setting? Just two?

**Comment by Rub4ek** [comment]
@epogrebnyak how about test settings?

**Comment by epogrebnyak** [comment]
Right!

23 сент. 2017 г. 21:39 пользователь "Rub4ek" <notifications@github.com>
написал:
