### ISSUE TITLE
Import error for AUTH_PASSWORD_VALIDATORS

### ISSUE THREAD

**Issue by Rub4ek** [mini-kep/full-app#22]
There is AUTH_PASSWORD_VALIDATORS setting in settings.py with validators like
```
django.contrib.authentication.password_validation.UserAttributeSimilarityValidator
```
that raises import error. 

So `django.contrib.authentication` should be changed to `django.contrib.auth`

**Comment by epogrebnyak** [comment]
Maybe this is django  version problem? Which version do you use?

23 сент. 2017 г. 20:11 пользователь "Rub4ek" <notifications@github.com>
написал:

**Comment by Rub4ek** [comment]
The one specified in `reqirements.txt`

**Comment by epogrebnyak** [comment]
When does the issue arise? Need more information from you to be able to
replicate the problem.

Ideally, need a test that is failing on you setup and see if itfails on
travis.

23 сент. 2017 г. 20:19 пользователь "Rub4ek" <notifications@github.com>
написал:

**Comment by Rub4ek** [comment]
@epogrebnyak try to change password in `/admin/`.

Or using `manage.py shell `
```
from django.contrib.auth import get_user_model
User = get_user_model()
u = User.objects.get(username='admin')
u.set_password('qwerty')
u.save()
```

**Comment by Rub4ek** [comment]
@epogrebnyak also take a look at docs for 1.11
https://docs.djangoproject.com/en/1.11/topics/auth/passwords/#enabling-password-validation
