### ISSUE TITLE
question: why python 2.7?

### ISSUE THREAD

**Issue by Rub4ek** [mini-kep/full-app#27]
I saw there is python 2.7 defined in travis config:
https://github.com/mini-kep/full-app/blob/master/.travis.yml#L3

Why not 3.5 or even 3.6. The future is here :) 
Parser works with 3.6 for example:
https://github.com/mini-kep/parser-rosstat-kep/blob/master/.travis.yml#L3

**Comment by epogrebnyak** [comment]
I fully agree we just need 3.6

26 сент. 2017 г. 14:08 пользователь "Alexey Kuznetsov" <
notifications@github.com> написал:

**Comment by tinivir** [comment]
@Rub4ek in Travis config defined a project version of Python. The project is on 2.7 Python. 2.7 is stable fully version. What features of 3.6 Python do you use in parser, or we plan to use in full-app?

**Comment by epogrebnyak** [comment]
Everyone, we have to migrate to 3.6, no 2.7.

26 сент. 2017 г. 15:30 пользователь "tinivir" <notifications@github.com>
написал:

**Comment by Rub4ek** [comment]
@tinivir it works fine at least on 3.5, cuz I use 3.5 for it. I, to be honest, find out that it was developed on 2.7 only today =)

**Comment by epogrebnyak** [comment]
It appears as very stable version, capable to run on 3,* indeed, but we have to move to 3.6.

**Comment by Rub4ek** [comment]
@epogrebnyak, I just checked packages that are used in the project:

*Django 1.11*
Python: 2.7, 3.4, 3.5, 3.6

*djangorestframework 3.x*
Python: 2.7, 3.2, 3.3, 3.4, 3.5, 3.6

*django-filter*
Python: 2.7, 3.3, 3.4, 3.5

*pytz*
Python: 2.4 or higher

So not sure about *django-filter*. Maybe just not up to date docs. Need to check

**Comment by tinivir** [comment]
I've already update to 3.6 https://github.com/mini-kep/full-app/commit/5d3ca418bb109557ee2a3b179f8fc5a77ced6ea4
