### ISSUE TITLE
ci: may use Travis + may need to change <tests.py> location and filename

### ISSUE THREAD

**Issue by epogrebnyak** [mini-kep/full-app#3]
pytest sees no tests right away. for Travis to work we need:

- [ ] the tests we have must be discoverable by pytest or unittest or some other call that we put in travis.yml, sample [here](https://github.com/mini-kep/parser-rosstat-kep/blob/master/.travis.yml#L10-L11)
- [ ] in flask there is internal procedure to test urls and associated actions, as in [here](http://flask.pocoo.org/docs/0.12/testing/#the-testing-skeleton), uses ```.test_client()``` method. Anythign similar in Django?

**Comment by epogrebnyak** [comment]
But maybe pytest will discover existing tests.py right away

**Comment by epogrebnyak** [comment]
pytest sees no tests right away. for Travis to work we need:

- [ ] the tests we have must be discoverable by pytest or unittest or some other call that we put in travis.yml, sample [here](https://github.com/mini-kep/parser-rosstat-kep/blob/master/.travis.yml#L10-L11)
- [ ] in flask there is internal procedure to test urls and associated actions, as in [here](http://flask.pocoo.org/docs/0.12/testing/#the-testing-skeleton), uses ```.test_client()``` method. Anythign similar in Django?

**Comment by epogrebnyak** [comment]
@tinivir - can you see if we can setup Travis for this project?

**Comment by tinivir** [comment]
I deploy travis to master now with tests. But config it only for dev. Also update tests #15

**Comment by epogrebnyak** [comment]
@tinivir - can you put little Travis badge in README.md ?

**Comment by epogrebnyak** [comment]
As a closing remark - ```manage.py test``` runs tests smoothly for django, but hides what tests are run. This way we do not see mcuh what is covered. Maybe there is a more verboe output for this command.
