### ISSUE TITLE
isolate User and Group from Datapoints

### ISSUE THREAD

**Issue by epogrebnyak** [mini-kep/full-app#5]
User,  Group are infrastructure classes, I woudl prefer to see them outside of the .api folder, and leave there only what is related to Datapoints. Even though User, Group are small, better isolate them

Possible solutions: 
>Правда я думаю скорее это подмодуль. Вообще каждая модель будет иметь соответствующий модуль состоящий из model-serializer-view

**Comment by epogrebnyak** [comment]
I like user and Group are isolated now, but for future refactoring -- maybe we can consider templating the project under <https://github.com/osminogin/cookiecutter-django-ultimate> or some of the conventions proposed.

The reason I like the template is that it promises us the following:
- heroku support
- apparently - switching configurations 
- user module is isolated by default
- pytest ready 

There are other templates as <https://github.com/pydanny/cookiecutter-django>, but one above seems cleanest. 

@tinivir - your opinion?

**Comment by epogrebnyak** [comment]
I think we need settings branching as in <https://stackoverflow.com/questions/1626326/how-to-manage-local-vs-production-settings-in-django/15325966#15325966>

**Comment by tinivir** [comment]
Cookiecutter  - ok. We will do it after our project will be really stable I think.

**Comment by epogrebnyak** [comment]
Let me put enw separate issues and close this. I agree template will be a step good for a stable version.
